### ISSUE TITLE
WG 小组组长需在提交报名后 5 个工作日内提交一个基于此版本的分支

### ISSUE THREAD

**Issue by YKG** [YKG/hptc-shichendahai#9]
https://github.com/pingcap/community/blame/master/challenge-programs/high-performance-tidb-challenge-cn.md#L109

@liufuyang 你看抽空给搞下？

**Comment by liufuyang** [comment]
这个其实没啥, 意思就是去你的repo 去 fork tidb, tikv, pd 的一个特定版本, 然后在这个版本上进行你的改动. 应该不用着急吧. 不过我可以先弄一下.

你确定不想在自己的fork上直接搞?

**Comment by liufuyang** [comment]
Anyway 我fork好了, 标准的hash都在我fork的master上了. 也加了你们作为collaborator,应该可以直接push代码到我的fork里(不需要再fork这个fork).
https://github.com/liufuyang/tidb

Tikv he PD也fork了, 但咱们要不怎么改上面代码的话, 你用这个fork或者upstream的标准hash版本都一样的...不知道他们为啥要五天内搞这些...
https://github.com/liufuyang/tikv
https://github.com/liufuyang/pd

**Comment by liufuyang** [comment]
你要觉得自己fork方便就用自己的就可以了 👍

**Comment by liufuyang** [comment]
感觉这个可以close掉了把?
